# TALLER 2

https://r2022.netlify.app/

In [1]:
install.packages("readxl")
library(readxl)
install.packages("readr")
library(readr)
install.packages("stringr")
library(stringr)
install.packages("hash")
library(hash)

Installing package into ‘/work/.R/library’
(as ‘lib’ is unspecified)

Warning message in install.packages("readxl"):
“installation of package ‘readxl’ had non-zero exit status”
Installing package into ‘/work/.R/library’
(as ‘lib’ is unspecified)

Warning message in install.packages("readr"):
“installation of package ‘readr’ had non-zero exit status”
Installing package into ‘/work/.R/library’
(as ‘lib’ is unspecified)

Installing package into ‘/work/.R/library’
(as ‘lib’ is unspecified)

hash-2.2.6.2 provided by Decision Patterns




## Películas

### Importe las variables Title, Year, Director y Country. 

In [2]:
csv_movies <- "/work/AiRoute/university-stuff/statistical_computing/sources/movie_avshotlength.csv"
movies <- read_delim(
                csv_movies,
                delim = ",",
                col_types=cols("?","?","?","?","-"),
                col_names = c("Titulo", "Año", "Director", "Pais"),
                skip = 1
                )
head(movies)

Titulo                   Año  Director          Pais
1 11:14                    2003 Marcks, Greg      USA 
2 21                       2008 Luketic, Robert   NA  
3 300                      2007 Snyder, Zack      USA 
4 2012                     2009 Emmerich, Roland  USA 
5 $                        1972 Brooks, Richard   NA  
6 *Batteries Not Included  1987 Robbins, Matthew  USA

Cuantas filas tiene el conjunto de datos resultante? 

In [3]:
#Tiene 11001 filas"
nrow(movies)

[1] 11001

Hay valores perdidos o missings? Cuantos? En qué variables?

In [4]:
#Tiene 11001 filas"
missings <- function(x) return(sum(is.na(x)))

In [5]:
#Si hay valores perdidos
#Hay 1386 valores perdidos
sum(apply(movies,2,missings))

[1] 1386

In [6]:
apply(movies,2,missings)
#Hay 4 valores perdios en la columna director, hay 15 en director y 1367 en la columna country

Titulo      Año Director     Pais 
       0        4       15     1367

### ¿Cuántas películas tienen solo 1 director(a)? ¿Cuántas películas tienen 2 directores(as)? ¿Cuántas películas tienen 3 o más directores(as)?

In [7]:
#Se le añade la columna con el numero de directores
movies <- within(movies,{
    n_directors <- str_count(Director, "&") + 1
})


In [8]:
#Hay 10751 peliculas con 1 director
num_dirs <- subset(movies, n_directors == 1)
str(num_dirs)
print(str_c("Peliculas : ", nrow(num_dirs)))

tibble [10,751 × 5] (S3: tbl_df/tbl/data.frame)
 $ Titulo     : chr [1:10751] "11:14" "21" "300" "2012" ...
 $ Año        : num [1:10751] 2003 2008 2007 2009 1972 ...
 $ Director   : chr [1:10751] "Marcks, Greg " "Luketic, Robert " "Snyder, Zack " "Emmerich, Roland " ...
 $ Pais       : chr [1:10751] "USA " NA "USA " "USA " ...
 $ n_directors: num [1:10751] 1 1 1 1 1 1 1 1 1 1 ...
[1] "Peliculas : 10751"


In [9]:
#Hay 233 peliculas con 2 directores(as)
num_dirs <- subset(movies, n_directors == 2)
str(num_dirs)
print(str_c("Peliculas : ", nrow(num_dirs)))

tibble [233 × 5] (S3: tbl_df/tbl/data.frame)
 $ Titulo     : chr [1:233] "21 Jump Street " "Aaltra " "About a Boy " "Adventures of Robin Hood, The " ...
 $ Año        : num [1:233] 2012 2004 2002 1938 2003 ...
 $ Director   : chr [1:233] "Lord, Phil & Miller, Christopher " "Delepine & Kerven " "Weitz, Chris & Paul " "Curtiz, M. & Keighley, W. " ...
 $ Pais       : chr [1:233] "USA " "BEL " NA "USA " ...
 $ n_directors: num [1:233] 2 2 2 2 2 2 2 2 2 2 ...
[1] "Peliculas : 233"


In [10]:
#Hay 2 peliculas con más de 3 directores(as)
num_dirs <- subset(movies, n_directors >= 3)
str(num_dirs)
print(str_c("Peliculas : ", nrow(num_dirs)))

tibble [2 × 5] (S3: tbl_df/tbl/data.frame)
 $ Titulo     : chr [1:2] "Airplane! " "Ruthless People "
 $ Año        : num [1:2] 1980 1986
 $ Director   : chr [1:2] "Abrahams, J. & Zucker, D. & J. " "Abrahams, J & Zucker, J&D "
 $ Pais       : chr [1:2] "USA " "USA "
 $ n_directors: num [1:2] 3 3
[1] "Peliculas : 2"


### ¿Cuántas y cuáles películas tienen nombres que incluyen números?

In [11]:
#Subconjunto donde pertenecen todos las cadenas de caracteres que contenga digitos
num_titles <- subset(movies, str_detect(Titulo, "\\d")) #Doble backslash para no generar conflictos con caracteres especiales
num_titles


Warning message in FUN(X[[i]], ...):
“input string 1 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid in this locale”
ERROR while rich displaying an object: Error in gsub(chr, html_specials[[chr]], text, fixed = TRUE): input string 1 is invalid in this locale

Traceback:
1. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
2. tryCatchList(expr, classes, parentenv, handlers)
3. tryCatchOne(expr, names, parentenv, handlers[[1L]])
4. doTryCatch(return(expr), name, parentenv, handler)
5. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mi

Titulo                                    Año  Director                   
1   11:14                                     2003 Marcks, Greg               
2   21                                        2008 Luketic, Robert            
3   300                                       2007 Snyder, Zack               
4   2012                                      2009 Emmerich, Roland           
5   [Rec]3 G\xe9nesis                         2012 Plaza, Paco                
6   1 Day                                     2009 Woolcock, Penny            
7   10                                        1979 Edwards, Blake             
8   10 Things I Hate About You                1999 Junger, Gil                
9   10 Years                                  2011 Linden, Jamie              
10  10,000 BC                                 2008 Emmerich, Roland           
11  101 Dalmatians                            1996 Herek, Stephen             
12  101 Reykjavik                             2000 Kormakur, Baltasar         
13  102 Dalmatians                            2000 Lima, Kevin                
14  10th. & Wolf                              2006 Morresco, Bobby            
15  127 Hours                                 2011 Boyle, Danny               
16  13 Assassins                              2010 Takashi Miike              
17  13 Going on 30                            2004 Winick, Gary               
18  13 Rue Madeleine                          1946 Hathaway, Henry            
19  13 Tzameti                                2005 Babluani, Gela             
20  13th. Warrior, The                        1999 McTiernan, John            
21  15 Minutes                                2001 Herzfeld, John             
22  16 Blocks                                 2006 Donner, Richard            
23  17 Again                                  2009 Steers, Burr               
24  1793                                      1914 Capellani, Albert          
25  1941                                      1979 Spielberg, Steven          
26  1942: A Love Story                        1994 Chopra, Vidhu Vinod        
27  2 Days in Paris                           2006 Delpy, Julie               
28  2 Fast, 2 Furious                         2003 Singleton, John            
29  20 Dates                                  1998 Berkowitz, Myles           
30  20 Fingers                                2004 Akbari, Mania              
... ...                                       ...  ...                        
322 Step Up 2: The Streets                    2008 Chu, Jun M.                
323 Storage 24                                2012 Roberts, Johannes          
324 Story of Wong Fei Hung, Part 1, The       1949 Wu Pang                    
325 Stuart Little 2                           2002 Minkoff, Rob               
326 Superbabies: Baby Geniuses 2              2003 Clark, Bob                 
327 Sweeney 2                                 1978 Clegg, Tom                 
328 Taking of Pelham 123, The                 2009 Scott, Tony                
329 Terminator 2: Judgement Day               1991 Cameron, James             
330 Terminator 3: The Rise of the Machines    2003 Mostow, Jonathan           
331 Things to do Before You're 30             2004 Shore, Simon               
332 Thir13en Ghosts                           2001 Beck, Steve                
333 Thunderbird 6                             1968 Lane, David                
334 To Gillian on Her 37th. Birthday          1996 Pressman, Michael          
335 Toy Story 2                               1999 Lasseter, Unkrich,         
336 Track 29                                  1988 Roeg, Nicolas              
337 Trail of '98, The                         1928 Brown, Clarence            
338 Transporter 2                             2005 Leterrier, L. & Yuen, Cory 
339 Transporter 3                             2008 Megaton, Olivier           
340 U-571                                     2000 Mos

In [12]:
#Hay 351 titulos con digitos
str(num_titles)
print(str_c("Titulos con numeros : ", nrow(num_titles)))

tibble [351 × 5] (S3: tbl_df/tbl/data.frame)
 $ Titulo     : chr [1:351] "11:14" "21" "300" "2012" ...
 $ Año        : num [1:351] 2003 2008 2007 2009 2012 ...
 $ Director   : chr [1:351] "Marcks, Greg " "Luketic, Robert " "Snyder, Zack " "Emmerich, Roland " ...
 $ Pais       : chr [1:351] "USA " NA "USA " "USA " ...
 $ n_directors: num [1:351] 1 1 1 1 1 1 1 1 1 1 ...
[1] "Titulos con numeros : 351"


### ¿Cuántas y cuáles películas tienen nombres que incluyen signos de puntuación?

In [13]:
puntuacion <- subset(movies, str_detect(Titulo, "[:punct:]"))#[?¿,.:;¡!\\'\\\"\\-\\_\\{\\}]
puntuacion

Warning message in FUN(X[[i]], ...):
“input string 1 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 3 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 3 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 3 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 3 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 3 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 3 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid in this locale”
ERROR while rich displaying an object: E

Titulo                                Año  Director               Pais
1    11:14                                 2003 Marcks, Greg           USA 
2    *Batteries Not Included               1987 Robbins, Matthew       USA 
3    [Rec]3 G\xe9nesis                     2012 Plaza, Paco            SPA 
4    10,000 BC                             2008 Emmerich, Roland       USA 
5    10th. & Wolf                          2006 Morresco, Bobby        USA 
6    13th. Warrior, The                    1999 McTiernan, John        USA 
7    1942: A Love Story                    1994 Chopra, Vidhu Vinod    IND 
8    2 Fast, 2 Furious                     2003 Singleton, John        NA  
9    20,000 Leagues Under the Sea          1954 Fleischer, Richard     USA 
10   2001: A Space Odyssey                 1968 Kubrick, Stanley       USA 
11   25th. Hour                            2002 Lee, Spike             USA 
12   3 Ninjas: High Noon at Mega Mountain  1998 McNamara, Sean         NA  
13   3.10 to Yuma                          1957 Daves, Delmer          USA 
14   3:10 to Yuma                          2007 Mangold, James         USA 
15   3:15                                  1986 Gross, Larry           USA 
16   300 Spartans, The                     1962 Mat\xe9, Rudolph       USA 
17   36 Quai des Orf?vres                  2004 Marchal, Olivier       FRA 
18   37.2 Le Matin                         1986 Beineix, Jean-Jacques  FRA 
19   4 Months, 3 Weeks and 2 Days          2007 Mungiu, Cristian       RUM 
20   4: Rise of the Silver Surfer          2007 Story, Tim             USA 
21   40 Year Old Virgin, The               2005 Apatow, Judd           USA 
22   42nd. Street                          1933 Bacon, Lloyd           USA 
23   48 HRS.                               1982 Hill, Walter           USA 
24   5,000 Finger of Dr. T, The            1953 Rowland, Roy           USA 
25   51st. State, The                      2001 Yu, Ronny              NA  
26   6th. Day, The                         2000 Spottiswoode, Roger    USA 
27   6th. Man, The                         1997 Miller, Randall        USA 
28   7th. Cavalry                          1956 Lewis, Joseph H.       USA 
29   7th. Dawn, The                        1964 Gilbert, Lewis         BRI 
30   7th. Heaven                           1927 Borzage, Frank         USA 
...  ...                                   ...  ...                    ... 
4112 Yellow Balloon, The                   1952 Lee-Thompson, J.       BRI 
4113 Yellow Cab Man, The                   1950 Donohue,               USA 
4114 Yellow Mountain, The                  1954 Hibbs, Jesse           USA 
4115 Yeux sans visage, les                 1959 Franju, Georges        FRA 
4116 You Can't Take it With You            1938 Capra, Frank           USA 
4117 You Don't Mess With the Zohan         2008 Dugan, Dennis          USA 
4118 You, Me and Dupree                    2006 Russo, Anthony & Joe   USA 
4119 You'd Be Surprised                    1926 Rosson, Arthur         USA 
4120 You'll Never Get Rich                 1941 Lanfield, Sidney       USA 
4121 Young Guns, The                       1956 Band, Albert           USA 
4122 Young Lions, The                      1958 Dmytryk, Edward        USA 
4123 Young Mr. Lincoln                     1939 Ford, John             USA 
4124 Young Ones, The                       1962 Furie, Sidney J.       BRI 
4125 Young Philadelphians, The             1959 Sherman, Vincent       USA 
4126 Young Poisoner's Handbook, The        1994 Ross, Benjamin         NA  
4127 Young Victoria, The                   2008 Vall\xe9e, Jean-Marc   NA  
4128 Young Warriors, The                   1967 Peyser, John           USA 
4129 Young Wive's Tale, The                1951 Cass, Henry            BRI 
4130 You're Dead\x85                       1999 Hurst, Andy            NA  
4131 You're My Everything                  1949 Lang, Walter           USA 
4132 Yours, Mine and Ours                  2005 Gosne

In [14]:
#Hay 4141 peliculas con signos de puntuacion
str(puntuacion)
print(str_c("Cuantas peliculas con signos de puntuacion : ", nrow(puntuacion)))

tibble [4,141 × 5] (S3: tbl_df/tbl/data.frame)
 $ Titulo     : chr [1:4141] "11:14" "*Batteries Not Included " "[Rec]3 G\xe9nesis " "10,000 BC " ...
 $ Año        : num [1:4141] 2003 1987 2012 2008 2006 ...
 $ Director   : chr [1:4141] "Marcks, Greg " "Robbins, Matthew " "Plaza, Paco " "Emmerich, Roland " ...
 $ Pais       : chr [1:4141] "USA " "USA " "SPA " "USA " ...
 $ n_directors: num [1:4141] 1 1 1 1 1 1 1 1 1 1 ...
[1] "Cuantas peliculas con signos de puntuacion : 4141"


### Cree un conjunto de datos con las películas que tienen solo 1 director(a)

Use la variable Director para crear una variable llamada Director2 teniendo en cuenta los siguientes parámetros: (a) Deben aparecer los nombre(s) y luego los apellido(s) del(de la) director(a) de la película separados por espacios sencillos y sin espacios al inicio ni al final; (b) Las iniciales de cada nombre y de cada apellido deben estar en letras mayúsculas.

In [15]:
#Subconjunto de movies
director_name <- subset(movies, n_directors == 1, select = -c(n_directors))
head(director_name)

Titulo                   Año  Director          Pais
1 11:14                    2003 Marcks, Greg      USA 
2 21                       2008 Luketic, Robert   NA  
3 300                      2007 Snyder, Zack      USA 
4 2012                     2009 Emmerich, Roland  USA 
5 $                        1972 Brooks, Richard   NA  
6 *Batteries Not Included  1987 Robbins, Matthew  USA

In [16]:
director_name <- within(director_name,{
        base <- str_split(director_name$Director, ",|\\.")
        Director2 <- str_c(sapply(base, tail, 1),sapply(base, head, 1))
        Director2 <- str_squish(Director2)
        Director2 <- str_to_title(Director2)
        rm(base)
})
head(director_name, n = 3)
tail(director_name, n = 3)

Titulo Año  Director         Pais Director2     
1 11:14  2003 Marcks, Greg     USA  Greg Marcks   
2 21     2008 Luketic, Robert  NA   Robert Luketic
3 300    2007 Snyder, Zack     USA  Zack Snyder

Titulo                     Año  Director             Pais Director2         
1 Zur Chronik von Grieshuus  1925 Gerlach, Arthur von  GER  Arthur Von Gerlach
2 Zwarte Boek                2006 Verhoeven, Paul      HOL  Paul Verhoeven    
3 Zweimal gelebt             1912 Mack. Max            GER  Max Mack

### Filtros

In [17]:
#Filtro Directores(as)
busca_director <- function(nombre_director) return (subset(director_name, Director2 == nombre_director))

In [18]:
#Limpiar a movies
movies <- within(movies,{
    Pais <- str_squish(Pais)
    rm(n_directors)
})
head(movies)

Titulo                   Año  Director          Pais
1 11:14                    2003 Marcks, Greg      USA 
2 21                       2008 Luketic, Robert   NA  
3 300                      2007 Snyder, Zack      USA 
4 2012                     2009 Emmerich, Roland  USA 
5 $                        1972 Brooks, Richard   NA  
6 *Batteries Not Included  1987 Robbins, Matthew  USA

In [19]:
#Filtro Paises
busca_pais <- function(nombre_pais) return (subset(movies, Pais == nombre_pais))

### ¿Cuántas y cuáles películas fueron dirigidas por Kathryn Bigelow?

In [20]:
# 6 Peliculas
busca_director("Kathryn Bigelow")
print(str_c("Numero de peliculas: ",nrow(busca_director("Kathryn Bigelow"))))

Titulo                Año  Director          Pais Director2      
1 Hurt Locker, The      2008 Bigelow, Kathryn  USA  Kathryn Bigelow
2 K-19: The Widowmaker  2002 Bigelow, Kathryn  USA  Kathryn Bigelow
3 Near Dark             1987 Bigelow, Kathryn  USA  Kathryn Bigelow
4 Point Break           1991 Bigelow, Kathryn  USA  Kathryn Bigelow
5 Strange Days          1995 Bigelow, Kathryn  USA  Kathryn Bigelow
6 Weight of Water, The  2000 Bigelow, Kathryn  NA   Kathryn Bigelow

[1] "Numero de peliculas: 6"


### ¿Cuantas y cuales películas fueron dirigidas por Martin Scorsese?

In [21]:
# 19 Peliculas
busca_director("Martin Scorsese")
print(str_c("Numero de peliculas: ",nrow(busca_director("Martin Scorsese"))))

Titulo                           Año  Director          Pais Director2      
1  After Hours                      1985 Scorsese, Martin  USA  Martin Scorsese
2  Age of Innocence, The            1993 Scorsese, Martin  USA  Martin Scorsese
3  Aviator, The                     2004 Scorsese, Martin  NA   Martin Scorsese
4  Bringing Out the Dead            1999 Scorsese, Martin  USA  Martin Scorsese
5  Cape Fear                        1991 Scorsese, Martin  USA  Martin Scorsese
6  Casino                           1995 Scorsese, Martin  USA  Martin Scorsese
7  Color of Money, The              1986 Scorsese, Martin  USA  Martin Scorsese
8  Departed, The                    2006 Scorsese, Martin  USA  Martin Scorsese
9  Gangs of New York                2002 Scorsese, Martin  USA  Martin Scorsese
10 GoodFellas                       1990 Scorsese, Martin  USA  Martin Scorsese
11 King of Comedy, The              1983 Scorsese, Martin  USA  Martin Scorsese
12 Kundun                           1997 Scorsese, Martin  USA  Martin Scorsese
13 Mean Streets                     1973 Scorsese, Martin  USA  Martin Scorsese
14 Mean Streets                     1973 Scorsese, Martin  USA  Martin Scorsese
15 New York Stories: Life Lessons   1989 Scorsese, Martin  USA  Martin Scorsese
16 New York, New York               1978 Scorsese, Martin  USA  Martin Scorsese
17 Raging Bull                      1980 Scorsese, Martin  USA  Martin Scorsese
18 Taxi Driver                      1976 Scorsese, Martin  USA  Martin Scorsese
19 Who's That Knocking At My Door?  1968 Scorsese, Martin  USA  Martin Scorsese

[1] "Numero de peliculas: 19"


### ¿Cuantas y cuales películas son Argentinas?

In [22]:
# 16 Peliculas
busca_pais("ARG")
print(str_c("Numero de peliculas: ",nrow(busca_pais("ARG"))))

Warning message in FUN(X[[i]], ...):
“input string 1 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid in this locale”
ERROR while rich displaying an object: Error in gsub(chr, html_specials[[chr]], text, fixed = TRUE): input string 1 is invalid in this locale

Traceback:
1. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
2. tryCatchList(expr, classes, parentenv, handlers)
3. tryCatchOne(expr, names, parentenv, handlers[[1L]])
4. doTryCatch(return(expr), name, parentenv, handler)
5. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mi

Titulo                              Año  Director                   Pais
1  Antena, la                          2007 Urdapilleta, Alejandro     ARG 
2  Aura, El                            2005 Bielinsky, Fabian          ARG 
3  Bonaerense, el                      2002 Trapero, Pablo             ARG 
4  Ci\xe9naga, la                      2001 Martel, Lucrecia           ARG 
5  Dia de suerte, un                   2002 Gugliotta, Sandra          ARG 
6  Glue                                2006 Dos Santos, Alexis         ARG 
7  Historias minimas                   2002 Sorin, Carlos              ARG 
8  I, the Worst of All                 1990 Bemberg, Maria Luisa       ARG 
9  Lady From the Shanghai Cinema, The  1987 Prado, Guilherme De Almei  ARG 
10 Lucky Day, A                        2002 Gugliotta, Sandra          ARG 
11 Nueve reinas                        2000 Bielinsky, Fabian          ARG 
12 Perro, el                           2004 Sorin, Carlos              ARG 
13 Prisioneros de la tierra            1939 Soffici, Mario             ARG 
14 Sangre de virgenes                  1967 Vieyra, Emilio             ARG 
15 Venganza del sexo, la               1967 Vieyra, Emilio             ARG 
16 Viaje, el                           1992 Solanas, Fernando          ARG

[1] "Numero de peliculas: 16"


### ¿Cuántas y cuáles películas son Mexicanas?

In [23]:
# 20 Peliculas
busca_pais("MEX")
print(str_c("Numero de peliculas: ",nrow(busca_pais("MEX"))))

Warning message in FUN(X[[i]], ...):
“input string 1 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid in this locale”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid in this locale”
ERROR while rich displaying an object: Error in gsub(chr, html_specials[[chr]], text, fixed = TRUE): input string 1 is invalid in this locale

Traceback:
1. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
2. tryCatchList(expr, classes, parentenv, handlers)
3. tryCatchOne(expr, names, parentenv, handlers[[1L]])
4. doTryCatch(return(expr), name, parentenv, handler)
5. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mi

Titulo                  Año  Director                Pais
1  Alamar                  2009 Gonzalez-Rubio, Pedro   MEX 
2  Alucarda                1975 Moctezuma, Juan Lopez   MEX 
3  Amores Perros           2000 Inarittu, Alejandro G.  MEX 
4  Angel externinador, el  1962 Bu?uel, Luis            MEX 
5  Come agua por chocolat  1993 Arau, Alfonso           MEX 
6  Cronos                  1992 Del Toro, Guillermo     MEX 
7  Danzon                  1991 Novaro, Maria           MEX 
8  D\xe9ficit              2007 Bernal, Gail Garcia     MEX 
9  Duck Season             2004 Eimbcke, Fernando       MEX 
10 El                      1953 Bu?uel, Luis            MEX 
11 KM 31: Kilometro 31     2005 Casta?eda, Rigoberto    MEX 
12 Latino Bar              1991 Leduc, Paul             MEX 
13 Littlest Outlaw, The    1955 Gavaldon, Roberto       MEX 
14 Perfume de violetas     2001 Sistach, Maryse         MEX 
15 Profundo carmesi        1996 Ripstein, Arturo        MEX 
16 Simon del desertio      1965 Bu?uel, Luis            MEX 
17 Somos lo que hay        2009 Grau, Jorge Michel      MEX 
18 Til Death, '            1993 Sarinana, Fernando      MEX 
19 Topo, el                1971 Jodorowsky, Alexander   MEX 
20 Y tu mama tambien       2001 Cuaron, Alfonso         MEX

[1] "Numero de peliculas: 20"


## Créditos

In [24]:
#Instalar los paquetes no funciono :(
install.packages("xts")
install.packages("sp")
install.packages("CASdatasets", repos = "http://cas.uqam.ca/pub/R/", type="source")
library(CASdatasets)


Installing package into ‘/work/.R/library’
(as ‘lib’ is unspecified)

Warning message in install.packages("xts"):
“installation of package ‘xts’ had non-zero exit status”
Installing package into ‘/work/.R/library’
(as ‘lib’ is unspecified)

Warning message in install.packages("sp"):
“installation of package ‘sp’ had non-zero exit status”
Installing package into ‘/work/.R/library’
(as ‘lib’ is unspecified)

Warning message:
“unable to access index for repository http://cas.uqam.ca/pub/R/src/contrib:
  cannot open URL 'http://cas.uqam.ca/pub/R/src/contrib/PACKAGES'”
Warning message:
“package ‘CASdatasets’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages”
Loading required package: xts

Loading required package: zoo


Attaching package: ‘zoo’


The following objects are masked from ‘package:base’:

    as.Date, as.Date.numer

In [25]:
#Instalar los paquetes no funciono asi que he descargado directamente el dataset 
#https://archive.ics.uci.edu/ml/datasets/Statlog+(German+Credit+Data)
#http://cas.uqam.ca/pub/web/CASdatasets-manual.pdf
credit <- read_delim("/work/AiRoute/university-stuff/statistical_computing/sources/german.data",
                     delim = " ",
                     col_names = c(
                         "Status_of_existing_checking_account",
                         "Duration_in_month",
                         "Credit_history",
                         "Purpose",
                         "Credit_amount",
                         "Savings_account/bonds",
                         "Present_employment_since",
                         "Installment_rate_in_percentage_of_disposable_income",
                         "Personal_status_and_sex",
                         "Other_debtors/guarantors",
                         "Present_residence_since",
                         "Property",
                         "Age_in_years",
                         "Other_installment_plans",
                         "Housing",
                         "Number_of_existing_credits_at_this_bank",
                         "Job",
                         "Number_of_people_being_liable_to_provide_maintenance_for",
                         "Telephone",
                         "Foreign_worker",
                         "Class")
)
credit$Class <- credit$Class - 1
head(credit)
str(credit)

Rows: 1000 Columns: 21
── Column specification ────────────────────────────────────────────────────────
Delimiter: " "
chr (13): Status_of_existing_checking_account, Credit_history, Purpose, Savi...
dbl  (8): Duration_in_month, Credit_amount, Installment_rate_in_percentage_o...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.


Status_of_existing_checking_account Duration_in_month Credit_history Purpose
1 A11                                  6                A34            A43    
2 A12                                 48                A32            A43    
3 A14                                 12                A34            A46    
4 A11                                 42                A32            A42    
5 A11                                 24                A33            A40    
6 A14                                 36                A32            A46    
  Credit_amount Savings_account/bonds Present_employment_since
1 1169          A65                   A75                     
2 5951          A61                   A73                     
3 2096          A61                   A74                     
4 7882          A61                   A74                     
5 4870          A61                   A73                     
6 9055          A65                   A73                     
  Installment_rate_in_percentage_of_disposable_income Personal_status_and_sex
1 4                                                   A93                    
2 2                                                   A92                    
3 2                                                   A93                    
4 2                                                   A93                    
5 3                                                   A93                    
6 2                                                   A93                    
  Other_debtors/guarantors ... Property Age_in_years Other_installment_plans
1 A101                     ... A121     67           A143                   
2 A101                     ... A121     22           A143                   
3 A101                     ... A121     49           A143                   
4 A103                     ... A122     45           A143                   
5 A101                     ... A124     53           A143                   
6 A101                     ... A124     35           A143                   
  Housing Number_of_existing_credits_at_this_bank Job 
1 A152    2                                       A173
2 A152    1                                       A173
3 A152    1                                       A172
4 A153    1                                       A173
5 A153    2                                       A173
6 A153    1                                       A172
  Number_of_people_being_liable_to_provide_maintenance_for Telephone
1 1                                                        A192     
2 1                                                        A191     
3 2                                                        A191     
4 2                                                        A191     
5 2                                                        A191     
6 2                                                        A192     
  Foreign_worker Class
1 A201           0    
2 A201           1    
3 A201           0    
4 A201           0    
5 A201           1    
6 A201           0

spc_tbl_ [1,000 × 21] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Status_of_existing_checking_account                     : chr [1:1000] "A11" "A12" "A14" "A11" ...
 $ Duration_in_month                                       : num [1:1000] 6 48 12 42 24 36 24 36 12 30 ...
 $ Credit_history                                          : chr [1:1000] "A34" "A32" "A34" "A32" ...
 $ Purpose                                                 : chr [1:1000] "A43" "A43" "A46" "A42" ...
 $ Credit_amount                                           : num [1:1000] 1169 5951 2096 7882 4870 ...
 $ Savings_account/bonds                                   : chr [1:1000] "A65" "A61" "A61" "A61" ...
 $ Present_employment_since                                : chr [1:1000] "A75" "A73" "A74" "A74" ...
 $ Installment_rate_in_percentage_of_disposable_income     : num [1:1000] 4 2 2 2 3 2 3 2 2 4 ...
 $ Personal_status_and_sex                                 : chr [1:1000] "A93" "A92" "A93" "A93" ...
 $ Other_debtors/g

In [26]:
install.packages("dplyr")
library(dplyr)
source("/work/AiRoute/university-stuff/statistical_computing/sources/mismacros.txt")

Installing package into ‘/work/.R/library’
(as ‘lib’ is unspecified)

Warning message in install.packages("dplyr"):
“installation of package ‘dplyr’ had non-zero exit status”

Attaching package: ‘dplyr’


The following objects are masked from ‘package:xts’:

    first, last


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



table  :  Month
weights: 1
                  Frequency
   | ----------------------
5  |                     31
6  |                     30
7  |                     31
8  |                     31
9  |                     30
   | ----------------------


### ¿Qué porcentaje de la cartera (número de créditos) corresponde a créditos “malos”?

Los créditos considerados "buenos" y "malos" se identifican como class = 0 y class = 1

In [27]:
#El 29.14% de numero de creditos de la cartera son malos
mytable(Number_of_existing_credits_at_this_bank	 ~ Class,data=credit,ord="freq")


table  :  Class
weights: Number_of_existing_credits_at_this_bank
                  Frequency             Percent(%)   Cumulative Frequency
   | ---------------------- ---------------------- ----------------------
0  |                    997                  70.86                    997
1  |                    410                  29.14                   1407
   | ---------------------- ---------------------- ----------------------
      Cumulative Percent(%)
   | ----------------------
0  |                  70.86
1  |                 100.00
   | ----------------------


El 29.14% de número de créditos de la cartera son malos

### ¿Qué porcentaje de la cartera (valor de los créditos) corresponde a créditos "malos"?

In [28]:
#El 36.12% del valor de los creditos de la cartera son malos
mytable(Credit_amount ~ Class,data=credit,ord="freq")


table  :  Class
weights: Credit_amount
                  Frequency             Percent(%)   Cumulative Frequency
   | ---------------------- ---------------------- ----------------------
0  |                2089820                  63.88                2089820
1  |                1181438                  36.12                3271258
   | ---------------------- ---------------------- ----------------------
      Cumulative Percent(%)
   | ----------------------
0  |                  63.88
1  |                 100.00
   | ----------------------


El 36.12% del valor de los creditos de la cartera son malos

### El porcentaje de la cartera (número de créditos) que corresponde a créditos "malos" es menor para los clientes con "buen" historial crediticio?

Historial de crédito
A30 : no se tomaron créditos/ todos los créditos se devolvieron debidamente
A31 : todos los créditos en este banco reembolsados debidamente
A32: créditos existentes reembolsados debidamente hasta ahora
A33 : retraso en el pago en el pasado
A34 : cuenta crítica/ otros créditos existentes (no en este banco)

In [31]:
#Historial de crédito
#A30 : no se tomaron créditos/ todos los créditos se devolvieron debidamente
#A31 : todos los créditos en este banco reembolsados debidamente
#A32: créditos existentes reembolsados debidamente hasta ahora
#A33 : retraso en el pago en el pasado
#A34 : cuenta crítica/ otros créditos existentes (no en este banco)

#Si, las mejores historias crediticias ocupan un menor porcentaje de numero de créditos malos (A30 , A31)  -> 20%. 
#Con la excepción de A32 que a pesar de no estar tan mal ocupa un 50%
#El 30% restante lo ocupan los peores historiales créditicios (A34, A33).

mytable(Number_of_existing_credits_at_this_bank	 ~ Credit_history,data=credit,subset= c(Class==1),ord="freq")


table  :  Credit_history
weights: Number_of_existing_credits_at_this_bank
                    Frequency             Percent(%)   Cumulative Frequency
     | ---------------------- ---------------------- ----------------------
A32  |                    194                  47.32                    194
A34  |                     91                  22.20                    285
A33  |                     47                  11.46                    332
A30  |                     44                  10.73                    376
A31  |                     34                   8.29                    410
     | ---------------------- ---------------------- ----------------------
        Cumulative Percent(%)
     | ----------------------
A32  |                  47.32
A34  |                  69.51
A33  |                  80.98
A30  |                  91.71
A31  |                 100.00
     | ----------------------


SI, las mejores historias crediticias ocupan un menor porcentaje de créditos malos (A30 , A31)  -> 20%. 

Con la excepción de A32 que a pesar de no ser una mala categoria ocupa casi un 50%

El 30% restante lo ocupan los peores historiales créditicios (A34, A33).

### El porcentaje de la cartera (en valor) que corresponde a créditos "malos" es menor para los clientes con "buen" historial crediticio?

In [32]:
#Sí, las mejores historias crediticias ocupan un menor porcentaje de valor de créditos malos (A30 , A31)  -> 20%. 
#Con la excepción de A32 que a pesar de no ser una mala categoría, ocupa más de un 50%
#Las peores categorías (A33, A34) ocupan poco más del 25%.
#Así que se podría determinar que los menores valores de créditos se asocian a buenas historias crediticias, sin embargo, la diferencia no se acentúa tanto como en el número de créditos.

mytable(Credit_amount ~ Credit_history,data=credit,subset= c(Class==1),ord="freq")


table  :  Credit_history
weights: Credit_amount
                    Frequency             Percent(%)   Cumulative Frequency
     | ---------------------- ---------------------- ----------------------
A32  |                 636380                  53.86                 636380
A34  |                 204747                  17.33                 841127
A30  |                 138156                  11.69                 979283
A33  |                 107750                   9.12                1087033
A31  |                  94405                   7.99                1181438
     | ---------------------- ---------------------- ----------------------
        Cumulative Percent(%)
     | ----------------------
A32  |                  53.86
A34  |                  71.20
A30  |                  82.89
A33  |                  92.01
A31  |                 100.00
     | ----------------------


Sí, las mejores historias crediticias ocupan un menor porcentaje de valor de créditos malos (A30 , A31)  -> 20%. 
Con la excepción de A32 que a pesar de no ser una mala categoría, ocupa más de un 50%
Las peores categorías (A33, A34) ocupan poco más del 25%.
Así que se podría determinar que los menores valores de créditos se asocian a buenas historias crediticias, sin embargo, la diferencia no se acentúa tanto como en el número de créditos.

### El porcentaje de la cartera (número de créditos) que corresponde a créditos "malos" es menor para los clientes con empleos más estables?

Trabajo
A171: desempleado/no calificado - no residente
A172 : no calificado - residente
A173: empleado calificado/funcionario
A174 : gestión/ autónomo/empleado / funcionario altamente calificado

In [34]:
#Trabajo
#A171: desempleado/no calificado - no residente
#A172 : no calificado - residente
#A173: empleado calificado/funcionario
#A174 : gestión/ autónomo/empleado / funcionario altamente calificado

#No, Casi el 80% de numero de creditos malos corresponde a empleados bien calificados y con estabilidad
mytable(Number_of_existing_credits_at_this_bank ~ Job,data=credit,subset= c(Class==1),ord="freq")


table  :  Job
weights: Number_of_existing_credits_at_this_bank
                     Frequency             Percent(%)   Cumulative Frequency
      | ---------------------- ---------------------- ----------------------
A173  |                    256                  62.44                    256
A174  |                     72                  17.56                    328
A172  |                     71                  17.32                    399
A171  |                     11                   2.68                    410
      | ---------------------- ---------------------- ----------------------
         Cumulative Percent(%)
      | ----------------------
A173  |                  62.44
A174  |                  80.00
A172  |                  97.32
A171  |                 100.00
      | ----------------------


No, Casi el 80% de número de créditos malos corresponde a empleados bien calificados y con estabilidad

### El porcentaje de la cartera (valor de los créditos) que corresponde a créditos "malos" es menor para los clientes con empleos más estables?

In [35]:
#No, Poco menos del 90% de valor de creditos malos corresponde a empleados bien calificados y con estabilidad
mytable(Credit_amount ~ Job,data=credit,subset= c(Class==1),ord="freq")


table  :  Job
weights: Credit_amount
                     Frequency             Percent(%)   Cumulative Frequency
      | ---------------------- ---------------------- ----------------------
A173  |                 677533                  57.35                 677533
A174  |                 347654                  29.43                1025187
A172  |                 133703                  11.32                1158890
A171  |                  22548                   1.91                1181438
      | ---------------------- ---------------------- ----------------------
         Cumulative Percent(%)
      | ----------------------
A173  |                  57.35
A174  |                  86.77
A172  |                  98.09
A171  |                 100.00
      | ----------------------


No, poco menos del 90% de valor de créditos malos corresponde a empleados bien calificados y con estabilidad

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=cd2fca3f-dc64-4c71-8bd4-adda531fa911' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>